In [4]:
import numpy as np

file_path = './zeroD_power.npy'

data = np.load(file_path)

print(data)

[[[[[0.77557033 0.77405739 0.77085392 0.76645828 0.75966785]
    [0.77606032 0.77419473 0.77148359 0.76713554 0.76193743]
    [0.77196558 0.77056975 0.76392436 0.7593324  0.75322595]
    [0.76260604 0.75271517 0.75255871 0.74097076 0.73438789]
    [0.74212471 0.73666199 0.73671584 0.73132986 0.72511723]]

   [[0.79211617 0.79210041 0.79212922 0.79190714 0.79115947]
    [0.79210228 0.79215282 0.79207786 0.79193016 0.79143562]
    [0.79152362 0.79139238 0.79055655 0.79010181 0.78925369]
    [0.79061142 0.7886996  0.78853278 0.78634597 0.7842879 ]
    [0.78675845 0.78591086 0.78591246 0.78414437 0.78208712]]

   [[0.79222013 0.79230272 0.79223143 0.79222179 0.79217759]
    [0.79225373 0.79226766 0.79229806 0.79225256 0.79229821]
    [0.79235174 0.79244455 0.79240071 0.79226824 0.79224748]
    [0.7925001  0.79242865 0.79245799 0.79226134 0.77695973]
    [0.76220597 0.76219619 0.79229916 0.76335551 0.79169698]]

   [[0.79228309 0.7922614  0.79230468 0.79227722 0.79226684]
    [0.79229552 0.